apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-backend
  template:
    metadata:
      labels:
        app: cicd-backend
    spec:
      containers:
        - name: cicd-backend
          image: bhanuteja110/cicd-backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-backend-service
spec:
  type: NodePort
  selector:
    app: cicd-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
